export type ListingType = "SALE" | "RENT";

export type ListingCategory = "SHORTLET" | "NEWHOMES";

export type PreviewProperty = {
  id: string;
  title: string;
  description: string;
  price: number;
  listingType: ListingType;
  category?: ListingCategory;
  propertyType: string;
  address: string;
  city: string;
  state: string;
  bedrooms: number | null;
  bathrooms: number | null;
  sqft: number | null;
  images: { url: string; caption: string | null }[];
  status: "AVAILABLE" | "PENDING" | "SOLD" | "RENTED";
  agentId: string;
  agentName: string;
  agentPhone?: string;
  agentProfileId?: string;
  amenities: string[];
  furnished: boolean;
  parking: number;
  lotSize?: string;
  yearBuilt?: number;
  createdAt: string;
  updatedAt: string;
  confirmedAt: string;
  latitude: number;
  longitude: number;
  costs: {
    rent?: number;
    agencyFee?: number;
    legalFee?: number;
    serviceCharge?: number;
    caution?: number;
    other?: number;
  };
};

export const PREVIEW_PROPERTIES: PreviewProperty[] = [
  {
    id: "sample-1",
    title: "2 bedroom flat, Lekki Phase 1",
    description: "A bright, comfortable apartment in a convenient Lekki location with room for a small family and easy access to major roads.",
    price: 3_500_000,
    listingType: "RENT",
    propertyType: "APARTMENT",
    address: "Lekki Phase 1",
    city: "Lekki",
    state: "Lagos",
    bedrooms: 2,
    bathrooms: 2,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-1",
    agentName: "Adebayo Ogundele",
    agentPhone: "0803 000 0001",
    agentProfileId: "agent-1",
    amenities: ["Parking", "Security", "Generator"],
    furnished: false,
    parking: 1,
    createdAt: "2026-09-20",
    updatedAt: "2026-09-21",
    confirmedAt: "2026-09-21",
    latitude: 6.4385,
    longitude: 3.4356,
    costs: { rent: 3_500_000, agencyFee: 350_000, legalFee: 175_000, caution: 300_000, serviceCharge: 250_000 },
  },
  {
    id: "sample-2",
    title: "4 bedroom detached house, Ikeja GRA",
    description: "A spacious detached home with generous living areas, a useful floor plan and a central location for established Lagos households.",
    price: 45_000_000,
    listingType: "SALE",
    propertyType: "HOUSE",
    address: "Ikeja GRA",
    city: "Ikeja",
    state: "Lagos",
    bedrooms: 4,
    bathrooms: 5,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-2",
    agentName: "Ngozi Eze",
    agentPhone: "0803 000 0002",
    agentProfileId: "agent-2",
    amenities: ["Parking", "Security", "Borehole / water supply", "Estate / gated community"],
    furnished: false,
    parking: 3,
    createdAt: "2026-09-18",
    updatedAt: "2026-09-19",
    confirmedAt: "2026-09-19",
    latitude: 6.5965,
    longitude: 3.3421,
    costs: { legalFee: 2_250_000, agencyFee: 2_250_000, other: 1_000_000 },
  },
  {
    id: "sample-3",
    title: "Self contain, Yaba",
    description: "A compact self-contained home with straightforward access to transport, work areas and everyday amenities in Yaba.",
    price: 1_200_000,
    listingType: "RENT",
    propertyType: "APARTMENT",
    address: "Yaba",
    city: "Yaba",
    state: "Lagos",
    bedrooms: 1,
    bathrooms: 1,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-3",
    agentName: "Tunde Bakare",
    agentPhone: "0803 000 0003",
    agentProfileId: "agent-3",
    amenities: ["Security", "Borehole / water supply"],
    furnished: false,
    parking: 0,
    createdAt: "2026-09-17",
    updatedAt: "2026-09-17",
    confirmedAt: "2026-09-10",
    latitude: 6.5158,
    longitude: 3.3712,
    costs: { rent: 1_200_000, agencyFee: 120_000, caution: 100_000 },
  },
  {
    id: "sample-4",
    title: "3 bedroom terrace, Gbagada",
    description: "A newly completed terrace in a fresh Gbagada development, with flexible living space and a useful address close to local services and transport.",
    price: 28_000_000,
    listingType: "SALE",
    category: "NEWHOMES",
    propertyType: "HOUSE",
    address: "Gbagada",
    city: "Gbagada",
    state: "Lagos",
    bedrooms: 3,
    bathrooms: 4,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-5",
    agentName: "Chinedu Nwosu",
    agentPhone: "0803 000 0005",
    agentProfileId: "agent-5",
    amenities: ["Parking", "Security", "Generator"],
    furnished: false,
    parking: 2,
    createdAt: "2026-09-16",
    updatedAt: "2026-09-18",
    confirmedAt: "2026-09-18",
    latitude: 6.5536,
    longitude: 3.3889,
    costs: { legalFee: 1_400_000, agencyFee: 1_400_000 },
  },
  {
    id: "sample-5",
    title: "3 bedroom apartment, Victoria Island",
    description: "A furnished, serviced apartment available for short-let stays and annual rent, with a central island location and generous bedroom and bathroom count for a comfortable city home.",
    price: 6_000_000,
    listingType: "RENT",
    category: "SHORTLET",
    propertyType: "APARTMENT",
    address: "Victoria Island",
    city: "Victoria Island",
    state: "Lagos",
    bedrooms: 3,
    bathrooms: 3,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-1",
    agentName: "Adebayo Ogundele",
    agentPhone: "0803 000 0001",
    agentProfileId: "agent-1",
    amenities: ["Parking", "Security", "Generator", "Pool"],
    furnished: true,
    parking: 2,
    createdAt: "2026-09-15",
    updatedAt: "2026-09-16",
    confirmedAt: "2026-09-16",
    latitude: 6.4281,
    longitude: 3.4219,
    costs: { rent: 6_000_000, agencyFee: 600_000, legalFee: 300_000, caution: 500_000, serviceCharge: 400_000 },
  },
  {
    id: "sample-6",
    title: "5 bedroom duplex, Ikoyi",
    description: "A recently built five-bedroom duplex in a new gated Ikoyi development, with a substantial layout, strong access and a high-privacy setting.",
    price: 250_000_000,
    listingType: "SALE",
    category: "NEWHOMES",
    propertyType: "HOUSE",
    address: "Ikoyi",
    city: "Ikoyi",
    state: "Lagos",
    bedrooms: 5,
    bathrooms: 6,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-4",
    agentName: "Funmi Adeyemi",
    agentPhone: "0803 000 0004",
    agentProfileId: "agent-4",
    amenities: ["Parking", "Security", "Generator", "Estate / gated community", "Pool"],
    furnished: true,
    parking: 4,
    createdAt: "2026-09-12",
    updatedAt: "2026-09-14",
    confirmedAt: "2026-09-14",
    latitude: 6.4531,
    longitude: 3.4453,
    costs: { legalFee: 12_500_000, agencyFee: 12_500_000 },
  },
  {
    id: "sample-8",
    title: "Plot of land, Ajah",
    description: "A land opportunity in a growing corridor with a documented title and development potential for the right buyer.",
    price: 18_000_000,
    listingType: "SALE",
    propertyType: "LAND",
    address: "Ajah",
    city: "Ajah",
    state: "Lagos",
    bedrooms: null,
    bathrooms: null,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-6",
    agentName: "Aisha Bello",
    agentPhone: "0803 000 0006",
    agentProfileId: "agent-6",
    amenities: ["Security"],
    furnished: false,
    parking: 0,
    lotSize: "300 sqm",
    createdAt: "2026-09-11",
    updatedAt: "2026-09-13",
    confirmedAt: "2026-09-13",
    latitude: 6.4676,
    longitude: 3.5852,
    costs: {},
  },
  {
    id: "sample-9",
    title: "2 bedroom flat, Oniru",
    description: "A neat two-bedroom apartment with a practical layout and convenient access to the Victoria Island side of Lagos.",
    price: 4_200_000,
    listingType: "RENT",
    propertyType: "APARTMENT",
    address: "Oniru",
    city: "Oniru",
    state: "Lagos",
    bedrooms: 2,
    bathrooms: 3,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-1",
    agentName: "Adebayo Ogundele",
    agentPhone: "0803 000 0001",
    agentProfileId: "agent-1",
    amenities: ["Parking", "Security", "Generator"],
    furnished: false,
    parking: 1,
    createdAt: "2026-09-10",
    updatedAt: "2026-09-12",
    confirmedAt: "2026-09-12",
    latitude: 6.4358,
    longitude: 3.4458,
    costs: { rent: 4_200_000, agencyFee: 420_000, caution: 400_000 },
  },
  {
    id: "sample-10",
    title: "Furnished 1 bedroom short let, Old Ikoyi",
    description: "A fully furnished one-bedroom apartment available for short-let stays, with housekeeping, reliable power and easy access to Ikoyi and Victoria Island.",
    price: 4_500_000,
    listingType: "RENT",
    category: "SHORTLET",
    propertyType: "APARTMENT",
    address: "Old Ikoyi",
    city: "Ikoyi",
    state: "Lagos",
    bedrooms: 1,
    bathrooms: 1,
    sqft: null,
    images: [],
    status: "AVAILABLE",
    agentId: "agent-4",
    agentName: "Funmi Adeyemi",
    agentPhone: "0803 000 0004",
    agentProfileId: "agent-4",
    amenities: ["Parking", "Security", "Generator", "Borehole / water supply", "Pool"],
    furnished: true,
    parking: 1,
    createdAt: "2026-09-22",
    updatedAt: "2026-09-22",
    confirmedAt: "2026-09-22",
    latitude: 6.4478,
    longitude: 3.4316,
    costs: { rent: 4_500_000, agencyFee: 450_000, caution: 300_000, serviceCharge: 500_000 },
  },
];

export const PREVIEW_AGENTS = [
  {
    id: "agent-1",
    name: "Adebayo Ogundele",
    agency: "Harcourt Court Properties",
    initials: "AO",
    verified: true,
    areas: ["Victoria Island", "Ikoyi", "Oniru"],
    specialisations: ["Serviced apartments", "Short-let"],
    responseTime: "Usually replies within 2 hours",
    listings: 12,
    bio: "A Lagos property consultant focused on serviced apartments, short-let homes and well-placed residential listings.",
    phone: "0803 000 0001",
  },
  {
    id: "agent-2",
    name: "Ngozi Eze",
    agency: "Lekki Homes Ltd",
    initials: "NE",
    verified: true,
    areas: ["Lekki Phase 1", "Ajah", "Sangotedo"],
    specialisations: ["Family flats", "Estates"],
    responseTime: "Usually replies within 4 hours",
    listings: 9,
    bio: "Helping families find practical homes and estates across the Lekki corridor.",
    phone: "0803 000 0002",
  },
  {
    id: "agent-3",
    name: "Tunde Bakare",
    agency: "Mainland Realty",
    initials: "TB",
    verified: false,
    areas: ["Ikeja", "Yaba", "Surulere"],
    specialisations: ["Self contain", "Hostels"],
    responseTime: "Usually replies within a day",
    listings: 6,
    bio: "Covering mainland Lagos homes, student accommodation and affordable rental options.",
    phone: "0803 000 0003",
  },
  {
    id: "agent-4",
    name: "Funmi Adeyemi",
    agency: "Ikoyi Reserve",
    initials: "FA",
    verified: true,
    areas: ["Ikoyi", "Victoria Island"],
    specialisations: ["Luxury rentals", "Penthouses"],
    responseTime: "Usually replies within 1 hour",
    listings: 15,
    bio: "A specialist in premium Ikoyi and Victoria Island homes, including penthouses and luxury rentals.",
    phone: "0803 000 0004",
  },
  {
    id: "agent-5",
    name: "Chinedu Nwosu",
    agency: "Gbagada Estates",
    initials: "CN",
    verified: false,
    areas: ["Gbagada", "Magodo", "Kosofe"],
    specialisations: ["Terraces", "Bungalows"],
    responseTime: "Usually replies within 6 hours",
    listings: 4,
    bio: "A local consultant for terraces, bungalows and homes around Gbagada and Magodo.",
    phone: "0803 000 0005",
  },
  {
    id: "agent-6",
    name: "Aisha Bello",
    agency: "Yaba Living",
    initials: "AB",
    verified: true,
    areas: ["Yaba", "Surulere", "Ebute Metta"],
    specialisations: ["Studio flats", "New builds"],
    responseTime: "Usually replies within 3 hours",
    listings: 8,
    bio: "Helping renters and buyers find studio flats and new-build homes on the mainland.",
    phone: "0803 000 0006",
  },
] as const;

export const PREVIEW_PROPERTY_TYPES = [
  { value: "", label: "Any type" },
  { value: "APARTMENT", label: "Apartment" },
  { value: "HOUSE", label: "House" },
  { value: "TOWNHOUSE", label: "Townhouse" },
  { value: "CONDO", label: "Condo" },
  { value: "LAND", label: "Land" },
  { value: "COMMERCIAL", label: "Commercial" },
] as const;

export const PREVIEW_BUDGETS = [
  { label: "Any price", min: undefined, max: undefined },
  { label: "Under 2 million", min: undefined, max: 2_000_000 },
  { label: "2 to 5 million", min: 2_000_000, max: 5_000_000 },
  { label: "5 to 15 million", min: 5_000_000, max: 15_000_000 },
  { label: "Above 15 million", min: 15_000_000, max: undefined },
] as const;

export const PREVIEW_AREAS = [
  "Lekki",
  "Victoria Island",
  "Ikoyi",
  "Ikeja",
  "Yaba",
  "Surulere",
  "Ajah",
  "Magodo",
  "Gbagada",
  "Oniru",
] as const;
